name: Feature Request
description: Suggest an idea for this project
title: "Feature: "
type: Feature
assignees: []
body:
  - type: textarea
    id: current-problem
    attributes:
      label: Current problem
      description: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](/reduct-storage/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
